### ISSUE TITLE
Domoticz devices not added

### ISSUE THREAD

**Issue by giejay** [thijsdebets/networkdetectz#2]
Hi, I'm trying to use this script to keep track of my devices but I cannot seem to make it work....

I added the sh file to the crontab and I see the data dir getting filled with all the necessary files.

My NewDevices switch is also turning on in Domoticz, but there arent any new devices. Im sure the hardware index is correct. 

This is the log when running it by hand, a lot of status: ERR are appearing so that might be the issue. I can not see unfortenately which call is failing. When adding a virtual device by hand with the curl command in the script, it works fine. 

```

Resolving linuxnet.ca (linuxnet.ca)... 24.222.55.20
Connecting to linuxnet.ca (linuxnet.ca)|24.222.55.20|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

{
   "status" : "ERR"
}
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Mon 16 Jan 23:51:43 CET 2017 Status of b8:27:eb:b0:09:ce - 54 - 0 - Raspberry Pi Foundation,Mitchell Wood House,,Caldecote Cambridgeshire CB23 7NU,UNITED KINGDOM,MA-L (DOM-Name: Raspberry Pi Foundation,Mitchell Wood House,,Caldecote Cambridgeshire CB23 7NU,UNITED KINGDOM,MA-L ) in Domoticz is Off
1
Device is turned ON
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Counter is 0
Mon 16 Jan 23:51:43 CET 2017 Status of b8:27:eb:16:95:14 - 54 - 0 - Raspberry Pi Foundation,Mitchell Wood House,,Caldecote Cambridgeshire CB23 7NU,UNITED KINGDOM,MA-L (DOM-Name: Raspberry Pi Foundation,Mitchell Wood House,,Caldecote Cambridgeshire CB23 7NU,UNITED KINGDOM,MA-L ) in Domoticz is Off
1
Device is turned ON
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Counter is 0
Mon 16 Jan 23:51:43 CET 2017 Status of fc:52:8d:6a:ac:49 - 54 - 0 - Technicolor CH USA Inc. (DOM-Name: Technicolor CH USA Inc. ) in Domoticz is Off
1
Device is turned ON
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Counter is 0
Mon 16 Jan 23:51:43 CET 2017 Status of 54:fa:3e:06:1c:75 - 54 - 0 - Samsung Electronics Co.,LTD,416,Maetan 3Dong,Yeongtong-Gu,,Suwon Gyeonggi-Do 443742,KOREA, REPUBLIC OF,MA-L (DOM-Name: Samsung Electronics Co.,LTD,416,Maetan 3Dong,Yeongtong-Gu,,Suwon Gyeonggi-Do 443742,KOREA, REPUBLIC OF,MA-L ) in Domoticz is Off
1
Device is turned ON
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Counter is 0
Mon 16 Jan 23:51:43 CET 2017 Status of 54:fa:3e:06:1c:78 - 54 - 0 - Samsung Electronics Co.,LTD,416,Maetan 3Dong,Yeongtong-Gu,,Suwon Gyeonggi-Do 443742,KOREA, REPUBLIC OF,MA-L (DOM-Name: Samsung Electronics Co.,LTD,416,Maetan 3Dong,Yeongtong-Gu,,Suwon Gyeonggi-Do 443742,KOREA, REPUBLIC OF,MA-L ) in Domoticz is Off
1
Device is turned ON
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Counter is 0
Mon 16 Jan 23:51:43 CET 2017 Status of 00:04:4b:4b:1d:8f - 54 - 0 - NVIDIA,3535 Monroe St.,,Santa Clara CA 95051,UNITED STATES,MA-L (DOM-Name: NVIDIA,3535 Monroe St.,,Santa Clara CA 95051,UNITED STATES,MA-L ) in Domoticz is Off
1
Device is turned ON
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Counter is 0
Mon 16 Jan 23:51:43 CET 2017 Status of 00:60:34:0e:7f:3e - 54 - 0 - ROBERT BOSCH GmbH,POSTBOX 11 62,,D-64701 ERBACH,GERMANY,MA-L (DOM-Name: ROBERT BOSCH GmbH,POSTBOX 11 62,,D-64701 ERBACH,GERMANY,MA-L ) in Domoticz is Off
1
Device is turned ON
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Counter is 0
Mon 16 Jan 23:51:43 CET 2017 Status of 00:04:20:f6:a9:76 - 54 - 0 - Slim Devices, Inc.,12 South First St.,Suite 103,San Jose CA 95113,UNITED STATES,MA-L (DOM-Name: Slim Devices, Inc.,12 South First St.,Suite 103,San Jose CA 95113,UNITED STATES,MA-L ) in Domoticz is Off
1
Device is turned ON
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Counter is 0
Mon 16 Jan 23:51:43 CET 2017 Status of fc:aa:14:73:18:dd - 54 - 0 - GIGA-BYTE TECHNOLOGY CO.,LTD.,Pin-Jen City, Taoyuan, Taiwan, R.O.C.,,Pin-Jen Taoyuan 324,TAIWAN, PROVINCE OF CHINA,MA-L (DOM-Name: GIGA-BYTE TECHNOLOGY CO.,LTD.,Pin-Jen City, Taoyuan, Taiwan, R.O.C.,,Pin-Jen Taoyuan 324,TAIWAN, PROVINCE OF CHINA,MA-L ) in Domoticz is Off
1
Device is turned ON
HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "OK",
   "title" : "SwitchLight"
}
Counter
```

Edit: I see all the devices are getting assigned to the same index: 

Mon 16 Jan 23:57:55 CET 2017 New device added: b8:27:eb:b0:09:ce        54      (Unknown) by Raspberry Pi Foundation,Mitchell Wood House,,Caldecote Cambridgeshire CB23 7NU,UNITED KINGDOM,MA-L
Mon 16 Jan 23:57:55 CET 2017 New device added: b8:27:eb:16:95:14        54      (Unknown) by Raspberry Pi Foundation,Mitchell Wood House,,Caldecote Cambridgeshire CB23 7NU,UNITED KINGDOM,MA-L
Mon 16 Jan 23:57:55 CET 2017 New device added: fc:52:8d:6a:ac:49        54      (Unknown) by Technicolor CH USA Inc.
^C

That index already exists, thats the one of my last added device

**Comment by thijsdebets** [comment]
Hi giejay,

I thinnk you're on an old version, which had this issue. I fixed this and if you do a new pull, this should work again.
before you pull, please copy nwd-config to nwd-config.own
this will prevent loss of settings incase of future improvements to this config file.
Always compare nwd-config and nwd-config.own after an update!

you might want to manually fix create sensors and update data/arp-table.dom or remove the entries from data/arp-table.dom and data/ndw.log

**Comment by giejay** [comment]
I pulled your latest changes but that did not fix it unfortunately.

I did try to manually create the sensors and after updating and removing the entries from arp-table it all worked!

Removing them from nwd.log however, caused all my removed devices appearing again in arp-table so I'm keeping them in there for now. 

Thanks for your excellent script!

**Comment by giejay** [comment]
A question, is it possible to implement a timeout? Now I'm seeing a lot of: 

2017-01-17 13:10:17	On
2017-01-17 13:08:16	Off
2017-01-17 13:05:15	On
2017-01-17 13:03:14	Off
2017-01-17 13:00:14	On
2017-01-17 13:00:13	Off
2017-01-17 12:57:11	On
2017-01-17 12:53:12	Off
2017-01-17 12:50:12	On
2017-01-17 12:49:39	Off
2017-01-17 12:46:38	On
2017-01-17 12:46:26	Off
2017-01-17 12:44:12	On
2017-01-17 12:42:12	Off
2017-01-17 12:39:11	On
2017-01-17 12:38:12	Off

A timeout of for example 5 minutes would be perfect to avoid this. 

I allready tried the off delay in the switch, but that just delays it, not actually prevents it from being set to off

**Comment by thijsdebets** [comment]
Yes,

in the file nwd-config you can set the retry attempts (default 1) a bit higher, so that NWD waits a bit longer before the device is switched definitely off:
RetryAttempts=1         # 3 = retry 4 times (5 minutes), 1 = retry 2 = 3 minutes

for phones (especially iPhones) it is also worth while to add the bluetooth mac to bluetooth.dom like so:
BT__MAC__ADDRESS;descriptuon;mac1;mac2;mac3;etc
example:
CC:61:E5:57:35:AB;GSM Moto X Force;cc:61:e5:57:35:ac

then NWD will also use bluetooth detection in case network detection failes.

**Comment by giejay** [comment]
Ah perfect, lets try that:) 

I'm gonna try the bluetooth as soon as I've got a dongle for my raspberry;)

**Comment by thijsdebets** [comment]
I've done some improvements to the script. You might want to pull the
latest version.

Kind regards,
Thijs

Op di 17 jan. 2017 14:28 schreef GJ Compagner <notifications@github.com>:

**Comment by giejay** [comment]
Great! I'll do that, thanks for letting me know

**Comment by giejay** [comment]
Hi, a clean install of the script now gives me: 

cp: cannot stat ‘/home/pi/domoticz/networkdetectz/data/arp-table.dom’: No such file or directory
./nwd-arpscan.sh: line 245: /home/pi/domoticz/network2/data/arp-table.dom: No such file or directory
./nwd-arpscan.sh: line 249: /home/pi/domoticz/network2/data/arp-table.dom: No such file or directory
./nwd-arpscan.sh: line 253: /home/pi/domoticz/network2/data/arp-table.dom: No such file or directory

Edit: Hmm apparently it really wants the arp-table to be in the networkdetectz folder. Fixed that but now:

Read configuration
Check Domoticz status
Execute Arp-Scan
Inconsistency detected by ld.so: get-dynamic-info.h: 115: elf_get_dynamic_info: Assertion `info[20]->d_un.d_val == 17 || info[20]->d_un.d_val == 7' failed!
1
lets start
HTTP/1.1 200 OK
Content-Length: 24
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Access-Control-Allow-Origin: *

{
   "status" : "ERR"
}

Edit2: 

It seems like nothing is added to the files in the data folder:

-rwxrwxrwx 1 pi pi   0 Mar  4 11:38 arp-scan.lst
-rwxrwxrwx 1 pi pi   0 Mar  4 11:38 arp-scan.raw
-rwxrwxrwx 1 pi pi   0 Mar  4 11:00 arp-table.dom
-rwxrwxrwx 1 pi pi 268 Mar  4 11:38 devices.html
-rwxrwxrwx 1 pi pi 587 Mar  4 11:38 DomoticzStatus.dat
-rwxrwxrwx 1 pi pi   3 Mar  4 11:38 DomoticzStatus.on
-rwxrwxrwx 1 pi pi   1 Mar  4 10:52 THIS-IS-THE-WORKING-DIR

**Comment by thijsdebets** [comment]
I fixed the path issue, was still one full path in the script.
The second issue looks like the arp-scan application is not functioning properly. 
Are you running the script as 'pi' user? 
Can it do a manual 'sudo arp-scan -l'? What is the result?

**Comment by giejay** [comment]
Sorry, that seems to be an issue with my Pi, all sorts of weird errors appear when doing it manually and when trying to apt-get update the package. After a reboot it wouldnt boot properly anymore, seems my sd card is broken:( Now with a new sd card, the new version is working perfectly!

**Comment by thijsdebets** [comment]
Good to hear, you got me worried thete for a moment.
